### PR TITLE
EMpy VSim-ized 

### PR DESCRIPTION
**Pull request by DavidRimel**
added some features that allow my python script to match up vsim and empy mesh. also removed matlibplot dependences from this package so that we can build EMpy.

### CODE REVIEW

**Comment by jrobcary** [comment]
It might be better just to use try catch to make this matplotlib
resilient.  I.e.,
define haveMatplotLib to be true if it correctly imports.

Then upstream might be willing to accept a pull request.

John

**Comment by DavidRimel** [comment]
so somthing like this?

     haveMatplotLib = true

     try:
          import matlibplot
     catch importError:
          haveMatplotLib = false

     if haveMatplotLib:
   
          matplotlibFOO()

**Comment by jrobcary** [comment]
Yes....

All calls to matplotlib protected by "if haveMatplotLib"

John

**Comment by DavidRimel** [comment]
so i fixed up the code such that all the calls to pylab or matplot lib have a try/catch block to import those libs so if one never calls the plotting function (which my python wrapper for EMpy does not) then it should work fine.

i tested this on the latest nightly ( Feb 07 2017 ) and it seems to work fine!

so i would recommend that you decline this pull request because i already submitted a pull request to ibolla/EMpy so when it gets accepted then you can just update to the head.

**Pull request merged**
